
services:
  - type: web
    name: purnatraders
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.14
